services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres_db
    ports:
      - "5433:5432"   # host:container (change host port if 5432 is already used)
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - backend
    restart: always

networks:
  backend:

volumes:
  postgres_data:
